spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate

  datasource:
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    url: jdbc:mysql://${DB_URL}:3306/${DB_NAME}?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&tinyInt1isBit=false
  jackson:
    property-naming-strategy: SNAKE_CASE

cloudflare:
  zone: ${CLOUDFLARE_ZONE}
  auth-email: ${CLOUDFLARE_AUTH_EMAIL}
  auth-key: ${CLOUDFLARE_AUTH_KEY}